REGISTRY ?= ghcr.io/davano-innovation-lab
IMG ?= $(REGISTRY)/cupel-operator:$(IMAGE_TAG)
IMAGE_TAG ?= 0.2.4
NAMESPACE ?= cupel-system
CONTROLLER_TOOLS_VERSION ?= v0.17.2

# Must match scanners.DefaultRegistry and scanners.ImageTag in
# internal/scanners/catalog.go.
SCANNER_REGISTRY ?= $(REGISTRY)
SCANNER_TAG ?= $(IMAGE_TAG)

LOCALBIN ?= $(shell pwd)/bin
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
GOLANGCI_LINT ?= $(LOCALBIN)/golangci-lint
# The single pin for both local and CI use: CI runs `make lint`, so there is no
# second version to drift. Installed with `go install`, which builds it against
# the local toolchain — golangci-lint errors out when the Go version it was
# built with is older than the one go.mod targets, which is what a prebuilt
# binary from the marketplace action would hit.
GOLANGCI_LINT_VERSION ?= v1.62.2

# Stamped into the standalone CLI. Override on release: make cli VERSION=v0.2.4
VERSION ?= dev
CLI_LDFLAGS ?= -X main.version=$(VERSION)

.PHONY: all
all: build

##@ Development

.PHONY: manifests
manifests: controller-gen ## Generate CRDs and RBAC from kubebuilder markers.
	$(CONTROLLER_GEN) crd rbac:roleName=cupel-manager-role paths=./... \
		output:crd:artifacts:config=config/crd/bases \
		output:rbac:artifacts:config=config/rbac

.PHONY: generate
generate: controller-gen ## Generate DeepCopy methods.
	$(CONTROLLER_GEN) object:headerFile=hack/boilerplate.go.txt paths=./api/...

.PHONY: fmt
fmt:
	go fmt ./...

.PHONY: vet
vet:
	go vet ./...

.PHONY: test
test: fmt vet ## Run the unit test suite.
	go test ./... -race -coverprofile=cover.out

.PHONY: cover
cover: test ## Show per-package coverage.
	go tool cover -func=cover.out

.PHONY: test-mlflow
test-mlflow: ## Live MLflow integration test (needs Docker + the mlflow image).
	go test -tags mlflow_live -run TestMLflowLive ./internal/modelsource/ -v

.PHONY: test-s3
test-s3: ## Live S3 resolver test against MinIO (needs Docker).
	go test -tags s3_live -run TestS3Live ./internal/resolver/ -v

.PHONY: test-live
test-live: test-mlflow test-s3 ## Every integration test that needs real services.

.PHONY: lint
lint: golangci-lint ## Run the linters CI runs.
	$(GOLANGCI_LINT) run ./...

##@ Build

.PHONY: build
build: fmt vet ## Build all binaries.
	go build -o bin/cupel-manager ./cmd/manager
	go build -o bin/cupel-runner ./cmd/runner
	go build -ldflags "$(CLI_LDFLAGS)" -o bin/cupel ./cmd/cupel

.PHONY: cli
cli: ## Build the standalone inspector CLI (make cli VERSION=v0.2.4).
	go build -ldflags "$(CLI_LDFLAGS)" -o bin/cupel ./cmd/cupel

# GOOS/GOARCH pairs shipped as release binaries.
CLI_PLATFORMS ?= darwin/amd64 darwin/arm64 linux/amd64 linux/arm64

.PHONY: cli-release
cli-release: ## Cross-compile the CLI for every release platform into dist/.
	@mkdir -p dist
	@for platform in $(CLI_PLATFORMS); do \
		os=$${platform%/*}; arch=$${platform#*/}; \
		out=dist/cupel-$(VERSION)-$$os-$$arch; \
		echo "building $$out"; \
		GOOS=$$os GOARCH=$$arch CGO_ENABLED=0 \
			go build -ldflags "$(CLI_LDFLAGS)" -o $$out ./cmd/cupel || exit 1; \
	done

.PHONY: docker-build
docker-build: ## Build the operator image.
	docker build -t $(IMG) .

.PHONY: docker-push
docker-push:
	docker push $(IMG)

##@ Scanner images

.PHONY: scanners
scanners: ## Build every scanner image with databases baked in.
	$(MAKE) -C scanners build REGISTRY=$(SCANNER_REGISTRY) TAG=$(SCANNER_TAG)

.PHONY: scanners-push
scanners-push:
	$(MAKE) -C scanners push REGISTRY=$(SCANNER_REGISTRY) TAG=$(SCANNER_TAG)

.PHONY: scanners-buildx
scanners-buildx: ## Build and push every scanner image for amd64 and arm64.
	$(MAKE) -C scanners buildx REGISTRY=$(SCANNER_REGISTRY) TAG=$(SCANNER_TAG)

.PHONY: scanners-smoke
scanners-smoke: ## Run the scanner images against a planted artifact, air-gapped.
	$(MAKE) -C scanners smoke REGISTRY=$(SCANNER_REGISTRY) TAG=$(SCANNER_TAG)

.PHONY: scanner-fixtures
scanner-fixtures: ## Refresh the recorded real scanner output used by the parser tests.
	./hack/capture-scanner-fixtures.sh $(SCANNER_REGISTRY) $(SCANNER_TAG)

.PHONY: mirror-list
mirror-list: ## Print every image to mirror into an air-gapped registry.
	@echo $(IMG)
	@$(MAKE) -s -C scanners mirror REGISTRY=$(SCANNER_REGISTRY) TAG=$(SCANNER_TAG)

##@ Packaging

HELM_CHART ?= deploy/helm/cupel

.PHONY: helm-sync
helm-sync: manifests ## Copy generated CRDs and RBAC rules into the Helm chart.
	@rm -rf $(HELM_CHART)/crds && mkdir -p $(HELM_CHART)/crds
	@# Only actual CRDs: Helm rejects anything else in crds/, and that
	@# directory also holds a kustomization.yaml for the Kustomize path.
	@for f in config/crd/bases/*.yaml; do \
		case "$$(basename $$f)" in kustomization.yaml) continue;; esac; \
		cp "$$f" $(HELM_CHART)/crds/; \
	done
	@# The ClusterRole rules come from the kubebuilder markers via
	@# config/rbac/role.yaml; the chart holds only the rules list so the
	@# template can own the metadata. Edit the markers, never this file.
	@printf '# Generated by `make helm-sync` from config/rbac/role.yaml. Do not edit.\n' \
		> $(HELM_CHART)/rbac-rules.yaml
	@awk '/^rules:/{f=1;next} f' config/rbac/role.yaml >> $(HELM_CHART)/rbac-rules.yaml
	@echo "synced $$(ls $(HELM_CHART)/crds | wc -l | tr -d ' ') CRDs and the ClusterRole rules"

.PHONY: stress
stress: ## Run the load and adversarial tests. Minutes, not seconds.
	go test -tags stress ./internal/stress/ -v -timeout 45m

.PHONY: helm-lint
helm-lint: helm-sync ## Lint and render the chart in every cert mode.
	helm lint $(HELM_CHART)
	@for mode in openshift cert-manager; do \
		echo "--- rendering certMode=$$mode"; \
		helm template cupel $(HELM_CHART) --namespace cupel-system \
			--set webhook.certMode=$$mode > /dev/null || exit 1; \
	done
	@echo "--- rendering with monitoring + extra scan namespaces"
	@helm template cupel $(HELM_CHART) --namespace cupel-system \
		--set metrics.serviceMonitor.enabled=true \
		--set metrics.prometheusRule.enabled=true \
		--set scanner.additionalNamespaces='{team-a,team-b}' > /dev/null

.PHONY: helm-package
helm-package: helm-lint ## Package the chart (make helm-package VERSION=v0.2.4).
	helm package $(HELM_CHART) --version $(VERSION:v%=%) --app-version $(VERSION:v%=%) -d dist/

.PHONY: kustomize-build
kustomize-build: manifests ## Render the Kustomize overlays.
	kubectl kustomize config/default
	@echo "--- overlays ---"
	@for o in config/overlays/*/; do echo "== $$o"; kubectl kustomize $$o > /dev/null && echo "   ok"; done

##@ Deployment

.PHONY: install
install: manifests ## Install CRDs into the cluster.
	@# Applied through kustomize rather than as a directory: config/crd/bases
	@# also holds a kustomization.yaml for the Kustomize path, and
	@# `kubectl apply -f <dir>` tries to apply that as a resource and fails.
	kubectl apply -k config/crd/bases

.PHONY: uninstall
uninstall:
	kubectl delete --ignore-not-found -k config/crd/bases

.PHONY: deploy
deploy: install ## Deploy the operator.
	# Namespace first: everything below is created inside it.
	kubectl apply -f config/namespace.yaml
	kubectl apply -f config/rbac
	kubectl apply -f config/manager
	kubectl apply -f config/webhook

.PHONY: undeploy
undeploy:
	kubectl delete --ignore-not-found -f config/webhook
	kubectl delete --ignore-not-found -f config/manager
	kubectl delete --ignore-not-found -f config/rbac
	kubectl delete --ignore-not-found -f config/namespace.yaml

##@ Tools

$(LOCALBIN):
	mkdir -p $(LOCALBIN)

.PHONY: controller-gen
controller-gen: $(LOCALBIN)
	@test -x $(CONTROLLER_GEN) || \
		GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_TOOLS_VERSION)

.PHONY: golangci-lint
golangci-lint: $(LOCALBIN)
	@test -x $(GOLANGCI_LINT) || \
		GOBIN=$(LOCALBIN) go install github.com/golangci/golangci-lint/cmd/golangci-lint@$(GOLANGCI_LINT_VERSION)

.PHONY: help
help:
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} \
		/^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2 } \
		/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(MAKEFILE_LIST)
