//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactException) DeepCopyInto(out *ArtifactException) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactException.
func (in *ArtifactException) DeepCopy() *ArtifactException {
	if in == nil {
		return nil
	}
	out := new(ArtifactException)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactException) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactExceptionList) DeepCopyInto(out *ArtifactExceptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactException, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactExceptionList.
func (in *ArtifactExceptionList) DeepCopy() *ArtifactExceptionList {
	if in == nil {
		return nil
	}
	out := new(ArtifactExceptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactExceptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactExceptionSpec) DeepCopyInto(out *ArtifactExceptionSpec) {
	*out = *in
	if in.FindingIDs != nil {
		in, out := &in.FindingIDs, &out.FindingIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApprovedByGroups != nil {
		in, out := &in.ApprovedByGroups, &out.ApprovedByGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApprovedAt != nil {
		in, out := &in.ApprovedAt, &out.ApprovedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactExceptionSpec.
func (in *ArtifactExceptionSpec) DeepCopy() *ArtifactExceptionSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactExceptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactExceptionStatus) DeepCopyInto(out *ArtifactExceptionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactExceptionStatus.
func (in *ArtifactExceptionStatus) DeepCopy() *ArtifactExceptionStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactExceptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactRef) DeepCopyInto(out *ArtifactRef) {
	*out = *in
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactRef.
func (in *ArtifactRef) DeepCopy() *ArtifactRef {
	if in == nil {
		return nil
	}
	out := new(ArtifactRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScan) DeepCopyInto(out *ArtifactScan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScan.
func (in *ArtifactScan) DeepCopy() *ArtifactScan {
	if in == nil {
		return nil
	}
	out := new(ArtifactScan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactScan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanList) DeepCopyInto(out *ArtifactScanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactScan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanList.
func (in *ArtifactScanList) DeepCopy() *ArtifactScanList {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactScanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanPolicy) DeepCopyInto(out *ArtifactScanPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanPolicy.
func (in *ArtifactScanPolicy) DeepCopy() *ArtifactScanPolicy {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactScanPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanPolicyList) DeepCopyInto(out *ArtifactScanPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactScanPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanPolicyList.
func (in *ArtifactScanPolicyList) DeepCopy() *ArtifactScanPolicyList {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactScanPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanPolicySpec) DeepCopyInto(out *ArtifactScanPolicySpec) {
	*out = *in
	if in.Scanners != nil {
		in, out := &in.Scanners, &out.Scanners
		*out = make([]ScannerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Rules.DeepCopyInto(&out.Rules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanPolicySpec.
func (in *ArtifactScanPolicySpec) DeepCopy() *ArtifactScanPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanReport) DeepCopyInto(out *ArtifactScanReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Summary.DeepCopyInto(&out.Summary)
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanReport.
func (in *ArtifactScanReport) DeepCopy() *ArtifactScanReport {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactScanReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanReportList) DeepCopyInto(out *ArtifactScanReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArtifactScanReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanReportList.
func (in *ArtifactScanReportList) DeepCopy() *ArtifactScanReportList {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArtifactScanReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanSpec) DeepCopyInto(out *ArtifactScanSpec) {
	*out = *in
	in.Artifact.DeepCopyInto(&out.Artifact)
	if in.Scanners != nil {
		in, out := &in.Scanners, &out.Scanners
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanSpec.
func (in *ArtifactScanSpec) DeepCopy() *ArtifactScanSpec {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactScanStatus) DeepCopyInto(out *ArtifactScanStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]ScannerResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RiskScore != nil {
		in, out := &in.RiskScore, &out.RiskScore
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactScanStatus.
func (in *ArtifactScanStatus) DeepCopy() *ArtifactScanStatus {
	if in == nil {
		return nil
	}
	out := new(ArtifactScanStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCheckpoint) DeepCopyInto(out *AuditCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCheckpoint.
func (in *AuditCheckpoint) DeepCopy() *AuditCheckpoint {
	if in == nil {
		return nil
	}
	out := new(AuditCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCheckpointList) DeepCopyInto(out *AuditCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuditCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCheckpointList.
func (in *AuditCheckpointList) DeepCopy() *AuditCheckpointList {
	if in == nil {
		return nil
	}
	out := new(AuditCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditCheckpointSpec) DeepCopyInto(out *AuditCheckpointSpec) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditCheckpointSpec.
func (in *AuditCheckpointSpec) DeepCopy() *AuditCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(AuditCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecord) DeepCopyInto(out *AuditRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecord.
func (in *AuditRecord) DeepCopy() *AuditRecord {
	if in == nil {
		return nil
	}
	out := new(AuditRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecordList) DeepCopyInto(out *AuditRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuditRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecordList.
func (in *AuditRecordList) DeepCopy() *AuditRecordList {
	if in == nil {
		return nil
	}
	out := new(AuditRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuditRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditRecordSpec) DeepCopyInto(out *AuditRecordSpec) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.Detail != nil {
		in, out := &in.Detail, &out.Detail
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditRecordSpec.
func (in *AuditRecordSpec) DeepCopy() *AuditRecordSpec {
	if in == nil {
		return nil
	}
	out := new(AuditRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProfile) DeepCopyInto(out *ComplianceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProfile.
func (in *ComplianceProfile) DeepCopy() *ComplianceProfile {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProfileList) DeepCopyInto(out *ComplianceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProfileList.
func (in *ComplianceProfileList) DeepCopy() *ComplianceProfileList {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProfileSpec) DeepCopyInto(out *ComplianceProfileSpec) {
	*out = *in
	if in.ModelSelector != nil {
		in, out := &in.ModelSelector, &out.ModelSelector
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attestations != nil {
		in, out := &in.Attestations, &out.Attestations
		*out = make([]ControlAttestation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exclusions != nil {
		in, out := &in.Exclusions, &out.Exclusions
		*out = make([]ControlExclusion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProfileSpec.
func (in *ComplianceProfileSpec) DeepCopy() *ComplianceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceProfileStatus) DeepCopyInto(out *ComplianceProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceProfileStatus.
func (in *ComplianceProfileStatus) DeepCopy() *ComplianceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceReport) DeepCopyInto(out *ComplianceReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceReport.
func (in *ComplianceReport) DeepCopy() *ComplianceReport {
	if in == nil {
		return nil
	}
	out := new(ComplianceReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceReportList) DeepCopyInto(out *ComplianceReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceReportList.
func (in *ComplianceReportList) DeepCopy() *ComplianceReportList {
	if in == nil {
		return nil
	}
	out := new(ComplianceReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceReportSpec) DeepCopyInto(out *ComplianceReportSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceReportSpec.
func (in *ComplianceReportSpec) DeepCopy() *ComplianceReportSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceReportStatus) DeepCopyInto(out *ComplianceReportStatus) {
	*out = *in
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = make([]FunctionSummary, len(*in))
		copy(*out, *in)
	}
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]ControlResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnmeasuredCharacteristics != nil {
		in, out := &in.UnmeasuredCharacteristics, &out.UnmeasuredCharacteristics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AssessedAt != nil {
		in, out := &in.AssessedAt, &out.AssessedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceReportStatus.
func (in *ComplianceReportStatus) DeepCopy() *ComplianceReportStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlAttestation) DeepCopyInto(out *ControlAttestation) {
	*out = *in
	if in.AttestedAt != nil {
		in, out := &in.AttestedAt, &out.AttestedAt
		*out = (*in).DeepCopy()
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlAttestation.
func (in *ControlAttestation) DeepCopy() *ControlAttestation {
	if in == nil {
		return nil
	}
	out := new(ControlAttestation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlExclusion) DeepCopyInto(out *ControlExclusion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlExclusion.
func (in *ControlExclusion) DeepCopy() *ControlExclusion {
	if in == nil {
		return nil
	}
	out := new(ControlExclusion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlResult) DeepCopyInto(out *ControlResult) {
	*out = *in
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlResult.
func (in *ControlResult) DeepCopy() *ControlResult {
	if in == nil {
		return nil
	}
	out := new(ControlResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeclaredModel) DeepCopyInto(out *DeclaredModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeclaredModel.
func (in *DeclaredModel) DeepCopy() *DeclaredModel {
	if in == nil {
		return nil
	}
	out := new(DeclaredModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSummary) DeepCopyInto(out *FunctionSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSummary.
func (in *FunctionSummary) DeepCopy() *FunctionSummary {
	if in == nil {
		return nil
	}
	out := new(FunctionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeylessIdentity) DeepCopyInto(out *KeylessIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeylessIdentity.
func (in *KeylessIdentity) DeepCopy() *KeylessIdentity {
	if in == nil {
		return nil
	}
	out := new(KeylessIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryConnector) DeepCopyInto(out *ModelRegistryConnector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryConnector.
func (in *ModelRegistryConnector) DeepCopy() *ModelRegistryConnector {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRegistryConnector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryConnectorList) DeepCopyInto(out *ModelRegistryConnectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelRegistryConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryConnectorList.
func (in *ModelRegistryConnectorList) DeepCopy() *ModelRegistryConnectorList {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryConnectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelRegistryConnectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryConnectorSpec) DeepCopyInto(out *ModelRegistryConnectorSpec) {
	*out = *in
	if in.RescanInterval != nil {
		in, out := &in.RescanInterval, &out.RescanInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]DeclaredModel, len(*in))
		copy(*out, *in)
	}
	if in.AuthSecretRef != nil {
		in, out := &in.AuthSecretRef, &out.AuthSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IncludeModels != nil {
		in, out := &in.IncludeModels, &out.IncludeModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WriteBack != nil {
		in, out := &in.WriteBack, &out.WriteBack
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryConnectorSpec.
func (in *ModelRegistryConnectorSpec) DeepCopy() *ModelRegistryConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegistryConnectorStatus) DeepCopyInto(out *ModelRegistryConnectorStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegistryConnectorStatus.
func (in *ModelRegistryConnectorStatus) DeepCopy() *ModelRegistryConnectorStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRegistryConnectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSecurityReport) DeepCopyInto(out *ModelSecurityReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSecurityReport.
func (in *ModelSecurityReport) DeepCopy() *ModelSecurityReport {
	if in == nil {
		return nil
	}
	out := new(ModelSecurityReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelSecurityReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSecurityReportList) DeepCopyInto(out *ModelSecurityReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ModelSecurityReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSecurityReportList.
func (in *ModelSecurityReportList) DeepCopy() *ModelSecurityReportList {
	if in == nil {
		return nil
	}
	out := new(ModelSecurityReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelSecurityReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSecurityReportSpec) DeepCopyInto(out *ModelSecurityReportSpec) {
	*out = *in
	in.Artifact.DeepCopyInto(&out.Artifact)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSecurityReportSpec.
func (in *ModelSecurityReportSpec) DeepCopy() *ModelSecurityReportSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSecurityReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSecurityReportStatus) DeepCopyInto(out *ModelSecurityReportStatus) {
	*out = *in
	out.CVEs = in.CVEs
	if in.Scanners != nil {
		in, out := &in.Scanners, &out.Scanners
		*out = make([]ScannerResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.ApprovedEnvironments != nil {
		in, out := &in.ApprovedEnvironments, &out.ApprovedEnvironments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSecurityReportStatus.
func (in *ModelSecurityReportStatus) DeepCopy() *ModelSecurityReportStatus {
	if in == nil {
		return nil
	}
	out := new(ModelSecurityReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRules) DeepCopyInto(out *PolicyRules) {
	*out = *in
	if in.MaxCriticalCVEs != nil {
		in, out := &in.MaxCriticalCVEs, &out.MaxCriticalCVEs
		*out = new(int32)
		**out = **in
	}
	if in.MaxHighCVEs != nil {
		in, out := &in.MaxHighCVEs, &out.MaxHighCVEs
		*out = new(int32)
		**out = **in
	}
	if in.BlockMalware != nil {
		in, out := &in.BlockMalware, &out.BlockMalware
		*out = new(bool)
		**out = **in
	}
	if in.BlockSecrets != nil {
		in, out := &in.BlockSecrets, &out.BlockSecrets
		*out = new(bool)
		**out = **in
	}
	if in.BlockUnsafeModel != nil {
		in, out := &in.BlockUnsafeModel, &out.BlockUnsafeModel
		*out = new(bool)
		**out = **in
	}
	if in.BlockModelDrift != nil {
		in, out := &in.BlockModelDrift, &out.BlockModelDrift
		*out = new(bool)
		**out = **in
	}
	if in.BlockUnexamined != nil {
		in, out := &in.BlockUnexamined, &out.BlockUnexamined
		*out = new(bool)
		**out = **in
	}
	if in.MaxHighModelFindings != nil {
		in, out := &in.MaxHighModelFindings, &out.MaxHighModelFindings
		*out = new(int32)
		**out = **in
	}
	if in.AllowedFormats != nil {
		in, out := &in.AllowedFormats, &out.AllowedFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockedFormats != nil {
		in, out := &in.BlockedFormats, &out.BlockedFormats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRules.
func (in *PolicyRules) DeepCopy() *PolicyRules {
	if in == nil {
		return nil
	}
	out := new(PolicyRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionRequest) DeepCopyInto(out *PromotionRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionRequest.
func (in *PromotionRequest) DeepCopy() *PromotionRequest {
	if in == nil {
		return nil
	}
	out := new(PromotionRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromotionRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionRequestList) DeepCopyInto(out *PromotionRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromotionRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionRequestList.
func (in *PromotionRequestList) DeepCopy() *PromotionRequestList {
	if in == nil {
		return nil
	}
	out := new(PromotionRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromotionRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionRequestSpec) DeepCopyInto(out *PromotionRequestSpec) {
	*out = *in
	if in.DecidedByGroups != nil {
		in, out := &in.DecidedByGroups, &out.DecidedByGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DecidedAt != nil {
		in, out := &in.DecidedAt, &out.DecidedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionRequestSpec.
func (in *PromotionRequestSpec) DeepCopy() *PromotionRequestSpec {
	if in == nil {
		return nil
	}
	out := new(PromotionRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionRequestStatus) DeepCopyInto(out *PromotionRequestStatus) {
	*out = *in
	if in.ObservedVerdictTime != nil {
		in, out := &in.ObservedVerdictTime, &out.ObservedVerdictTime
		*out = (*in).DeepCopy()
	}
	if in.ReviewTime != nil {
		in, out := &in.ReviewTime, &out.ReviewTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionRequestStatus.
func (in *PromotionRequestStatus) DeepCopy() *PromotionRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PromotionRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScannerResult) DeepCopyInto(out *ScannerResult) {
	*out = *in
	out.Severities = in.Severities
	out.Drift = in.Drift
	out.Unexamined = in.Unexamined
	if in.Produced != nil {
		in, out := &in.Produced, &out.Produced
		*out = new(bool)
		**out = **in
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScannerResult.
func (in *ScannerResult) DeepCopy() *ScannerResult {
	if in == nil {
		return nil
	}
	out := new(ScannerResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScannerSpec) DeepCopyInto(out *ScannerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScannerSpec.
func (in *ScannerSpec) DeepCopy() *ScannerSpec {
	if in == nil {
		return nil
	}
	out := new(ScannerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeverityCounts) DeepCopyInto(out *SeverityCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeverityCounts.
func (in *SeverityCounts) DeepCopy() *SeverityCounts {
	if in == nil {
		return nil
	}
	out := new(SeverityCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustedPublisher) DeepCopyInto(out *TrustedPublisher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustedPublisher.
func (in *TrustedPublisher) DeepCopy() *TrustedPublisher {
	if in == nil {
		return nil
	}
	out := new(TrustedPublisher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustedPublisher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustedPublisherList) DeepCopyInto(out *TrustedPublisherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrustedPublisher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustedPublisherList.
func (in *TrustedPublisherList) DeepCopy() *TrustedPublisherList {
	if in == nil {
		return nil
	}
	out := new(TrustedPublisherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrustedPublisherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustedPublisherSpec) DeepCopyInto(out *TrustedPublisherSpec) {
	*out = *in
	if in.KeylessIdentity != nil {
		in, out := &in.KeylessIdentity, &out.KeylessIdentity
		*out = new(KeylessIdentity)
		**out = **in
	}
	if in.URIPrefixes != nil {
		in, out := &in.URIPrefixes, &out.URIPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustedPublisherSpec.
func (in *TrustedPublisherSpec) DeepCopy() *TrustedPublisherSpec {
	if in == nil {
		return nil
	}
	out := new(TrustedPublisherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustedPublisherStatus) DeepCopyInto(out *TrustedPublisherStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustedPublisherStatus.
func (in *TrustedPublisherStatus) DeepCopy() *TrustedPublisherStatus {
	if in == nil {
		return nil
	}
	out := new(TrustedPublisherStatus)
	in.DeepCopyInto(out)
	return out
}
